### ISSUE TITLE
Missing refactoring files

### ISSUE THREAD

**Issue by zaprogrammer** [mjohnsullivan/dashcast#1]
Thanks @afitz0 & @efortuna for this episode of the Boring show. I enjoyed it.
It seems that you need to push the newly refactored classes :)

**Comment by afitz0** [comment]
🤦🏻‍♂️Classic case of a forgotten `git add`. Thanks for letting us know (and for watching)!! They should be pushed now.

**Comment by zaprogrammer** [comment]
yah exactly it happens 😃 .. that's why I prefer intellij 😸
